### ISSUE TITLE
NOT WORK discord POST

### ISSUE THREAD

**Issue by ilyasse005** [nfacha/PlaneAlert#15]
hello i have follow this 
![image](https://github.com/nfacha/PlaneAlert/assets/52047430/08acbd58-f296-455b-977c-b9665b9a7eab)

it not work i have change name and icao and i have put discord to receive data but noting happen can you help thanks

**Comment by nfacha** [comment]
> hello i have follow this ![image](https://user-images.githubusercontent.com/52047430/259593493-08acbd58-f296-455b-977c-b9665b9a7eab.png)
> 
> it not work i have change name and icao and i have put discord to receive data but noting happen can you help thanks

Hi!
Are you able top provide logs?

**Comment by nfacha** [comment]
Closing due to no further details being provided
